[project]
name = "kohya-ss-dataset-preparation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.1",
    "opencv-python-headless>=4.10.0.84",
    "ultralytics>=8.3.23",
]
